version: "3.9"
services:
  tandoor:
    build:
      args:
        ALPINE_VERSION: "latest"
        CONTAINER_VERSION: "1.5.11"
        TANDOOR_VERSION: "1.5.11"
      context: .
      dockerfile: container.build
      no_cache: true
      tags:
        - "tandoor:build"
        - "gautada/tandoor:build"
        - "gautada/tandoor:latest"
    image: "gautada/tandoor:latest"
    environment:
    - SECRET_KEY=${COMPOSE_YOUR_SECRET_KEY}
    - DB_ENGINE=django.db.backends.postgresql 
    - POSTGRES_HOST=${COMPOSE_POSTGRES_HOST}
    - POSTGRES_PORT=5432 
    - POSTGRES_USER=tandoor 
    - POSTGRES_PASSWORD=${COMPOSE_POSTGRES_PASSWORD}
    - POSTGRES_DB=tandoordb
    ports:
      - "8080:8080"
    volumes:
      - "Container:/mnt/volumes/container"
      - "Backup:/mnt/volumes/backup"
      - "Configmaps:/mnt/volumes/configmaps"
      - "Secrets:/mnt/volumes/secrets"

volumes:
  Container:
    external: true
    name: "Container"

  Backup:
    external: true
    name: "Backup"

  Configmaps:
    external: true
    name: "Configmaps"
    
  Secrets:
    external: true
    name: "Secrets"

