#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

ENTRYPOINT_PARAMS="$@"
. /etc/profile

CONTAINER_NAME="tandoor"

container_entrypoint() {
    if [ ! -f /opt/recipes/vue/webpack-stats.json ]; then
        echo "Running setup"
        cd /opt/recipes/vue
        /usr/bin/yarn install
        /usr/bin/yarn build
        /bin/rm /bin/rm -rvf babel.config.js babel.config.js.c node_modules/ package.json tsconfig.json
    fi
    cd /opt/recipes
    . /opt/recipes/boot.sh 
    # tail -f /dev/null
}

container_version() {
    /usr/bin/python -c "from cookbook import version_info; print(version_info.TANDOOR_VERSION);"
}
