#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

ENTRYPOINT_PARAMS="$@"
. /etc/profile

CONTAINER_NAME="tandoor"

container_entrypoint() {
 cd /recipes
 chmod +x boot.sh
 ./boot.sh 
}

container_version() {
 # /usr/bin/postgres --version | awk -F ' ' '{print $3}'
 echo "0.0.0"
}
